// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "summary": "Index",
                "responses": {}
            }
        },
        "/derp.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get DERP Map",
                "parameters": [
                    {
                        "enum": [
                            "alive",
                            "error",
                            "all"
                        ],
                        "type": "string",
                        "description": "alive|error|all",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "latency limit, e.g. 500ms",
                        "name": "latency-limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "bandwidth limit, e.g. 2Mbps",
                        "name": "bandwidth-limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
